apiVersion: v1
kind: ConfigMap
metadata:
  name: dep-config-map
data:
  mongo-connection-string: mongodb://cluster0-shard-00-00.ank2h.mongodb.net:27017,cluster0-shard-00-01.ank2h.mongodb.net:27017,cluster0-shard-00-02.ank2h.mongodb.net:27017/test?ssl=true&replicaSet=atlas-ypl89o-shard-0&authSource=admin&retryWrites=true&w=majority