apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs
spec:
  resources:
    requests:
      storage: 100Mi
  # volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
