apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  # clusterIP: None
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-stateful
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo-service
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: ishank162/mongodb
        # securityContext:
        #   runAsUser: 0
        # command:
        # - "mongod"
        #   - /bin/chown
        #   - -R
        #   - "777"
        #   - /data/db
        ports:
        - containerPort: 27017
          # name: web
      #   volumeMounts:
      #     - name: nfs-server
      #       mountPath: /data/db
      # volumes:
      #   - name: nfs-server
      #     persistentVolumeClaim:
      #       claimName: pvc-nfs
        # volumeMounts:
        # - name: mongo-pvc
        #   mountPath: /data/db
      #   volumeMounts:
      #     - mountPath: /home/ishank/mongo-data
      #       name:  mongo-host-data
      # volumes:
      #   - name: mongo-host-data
      #     hostPath:
      #       path: /home/ishank/mongo-data
      #       type: DirectoryOrCreate
  # volumeClaimTemplates:
  # - metadata:
  #     name: mongo-pvc
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     resources:
  #       requests:
  #         storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongo-service
        - name: ME_CONFIG_BASICAUTH_USERNAME
          value: "user1"
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          value: "pass1"
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  # type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    # nodePort: 30001
